version: "3.1"

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - ${PORT}:${PORT}

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
